import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ApolloWrapper } from "@/utils/apollo/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <div className="min-h-screen grid">{children}</div>
          <Toaster></Toaster>
        </ApolloWrapper>
      </body>
    </html>
  );
}
